version: "3"

services:
  chs-bakcend:
    build: .
    ports:
      - "5000:3000"
    env_file: 
      - .env

  redis:
    image: redis:alpine
    volumes: 
      - ./redis:/data
    cmd: "redis-server --appendonly yes"

  mongo:
    image: mongo
    volumes: 
      - ./mongo:/var/db
    